---
- name: Query Oracle Database Role and Switchover Status
  hosts: linuxdb
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query
        sqlplus -s / as sysdba <<EOF
        SET HEADING ON
        SET PAGESIZE 50
        SET FEEDBACK OFF
        SET LINESIZE 150
        COLUMN Thread FORMAT 999
        COLUMN "Last Sequence Received" FORMAT 999
        COLUMN "Last Sequence Applied" FORMAT 999
        COLUMN Difference FORMAT 999
        SELECT ARCH.THREAD# "Thread",
               ARCH.SEQUENCE# "Last Sequence Received",
               APPL.SEQUENCE# "Last Sequence Applied",
               (ARCH.SEQUENCE# - APPL.SEQUENCE#) "Difference"
        FROM (
          SELECT THREAD#, SEQUENCE#
          FROM V\$ARCHIVED_LOG
          WHERE (THREAD#, FIRST_TIME) IN (
            SELECT THREAD#, MAX(FIRST_TIME)
            FROM V\$ARCHIVED_LOG
            GROUP BY THREAD#
          )
        ) ARCH
        JOIN (
          SELECT THREAD#, SEQUENCE#
          FROM V\$LOG_HISTORY
          WHERE (THREAD#, FIRST_TIME) IN (
            SELECT THREAD#, MAX(FIRST_TIME)
            FROM V\$LOG_HISTORY
            GROUP BY THREAD#
          )
        ) APPL
        ON ARCH.THREAD# = APPL.THREAD#;
        EOF
      register: db_status
      ignore_errors: yes

    - name: Display the database status
      debug:
        msg: "Database Status:\n{{ db_status.stdout }}"
