---
- name: Primary
  hosts: 10.50.11.231
  tasks:
    - name: Ensure using mysql user
      shell: whoami
  
##    - name: Switch to mysql user
##      shell: su - mysql

    - name: Switch to mysqlsh
      shell: /apps/mysql/mysql-shell-8.0.38/bin/mysqlsh inno_cluster:mysql@10.50.11.231:3306 -- clusterset status
      register: cluster_status

##    - name: Get MySQL Cluster Set Status
##      shell: \c inno_cluster@10.50.11.231:3306
      
##    - name: Get MySQL Cluster Set Status
##      shell: clusterset status
##      register: cluster_status
       
    - name: Print Cluster Status
      debug:
        var: cluster_status.stdout

    - name: Check session lists
      shell: /apps/mysql/mysql-8.0.38/bin/mysql -uroot -pmysql123 -h127.0.0.1 -P3306 -e"show processlist;"
      register: session_lists

    - name: Print Session List
      debug:
        var: session_lists.stdout
      
